# Generated by Django 4.0.4 on 2022-04-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_alter_categories_label_alter_todo_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='label',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='events',
            name='end',
            field=models.DateTimeField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='events',
            name='start',
            field=models.DateTimeField(verbose_name='Start Date'),
        ),
    ]
